Improve initContainer to wait for ITS
Signed-off-by: francostellari <fstellari@gmail.com>

diff --git a/chart/templates/controller.yaml b/chart/templates/controller.yaml
--- a/chart/templates/controller.yaml
+++ b/chart/templates/controller.yaml
@@ -72,34 +72,49 @@ data:
     #!/bin/env bash
     # Get the in-cluster kubeconfig for KubeFlex Control Planes
     # get-kubeconfig.sh cp_name guess_its_name
+
+    # input parameters
     cp_name="${1%"-system"}" # cp name or cp namespace
-    guess_its_name="$2" # true: try guessing the name of the ibms CP
+    guess_its_name="$2" # true: try guessing the name of the ITS CP
+
+    # check if the CP name is valid or needs to be guessed
     if [ "$cp_name" == "" ] ; then
       if [ "$guess_its_name" == "true" ] ; then
-        for cp in `kubectl get controlplane -o name`; do
-          cp=${cp##*/} # separate just the CP name
-          if [ "$(kubectl get controlplane $cp -o jsonpath="{.metadata.labels['kflex\.kubestellar\.io/cptype']}")" == "its" ] ; then
-            if [ "$cp_name" == "" ] ; then
-              cp_name="$cp"
-            else
-              >&2 echo "ERROR: found more than one Control Plane of type its!"
-              exit 1
+        while [ "$cp_name" == "" ] ; do
+          for cp in `kubectl get controlplane -o name`; do
+            cp=${cp##*/} # separate just the CP name
+            if [ "$(kubectl get controlplane $cp -o jsonpath="{.metadata.labels['kflex\.kubestellar\.io/cptype']}")" == "its" ] ; then
+              if [ "$cp_name" == "" ] ; then
+                cp_name="$cp"
+                break 2
+              else
+                >&2 echo "ERROR: found more than one Control Plane of type its!"
+                exit 1
+              fi
             fi
-          fi
+          done
+          >&2 echo "Waiting for an ITS control plane to exist..."
+          sleep 10
         done
-        if [ "$cp_name" == "" ] ; then
-          >&2 echo "ERROR: no Control Plane of type its found!"
-          exit 2
-        fi
       else
         >&2 echo "ERROR: no Control Plane name specified!"
         exit 3
       fi
     fi
+
+    # wait for the CP to exists and be ready
+    while [[ $(kubectl get controlplane $cp_name -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}') != "True" ]]; do
+      >&2 echo "Waiting for \"$cp_name\" control plane to exist and be ready..."
+      sleep 10
+    done
+
+    # determine the secret name and namespace
     key=$(kubectl get controlplane $cp_name -o=jsonpath='{.status.secretRef.inClusterKey}')
     secret_name=$(kubectl get controlplane $cp_name -o=jsonpath='{.status.secretRef.name}')
     secret_namespace=$(kubectl get controlplane $cp_name -o=jsonpath='{.status.secretRef.namespace}')
+
     # get the kubeconfig in base64
+    >&2 echo "Getting \"$key\" from \"$secret_name\" secret in \"$secret_namespace\" for control plane \"$cp_name\"..."
     kubectl get secret $secret_name -n $secret_namespace -o=jsonpath="{.data.$key}"
 ---
 apiVersion: apps/v1
